### ISSUE TITLE
Question for what program did modification

### ISSUE THREAD

**Issue by potmo** [daniel-pedersen/SKQueue#14]
Hi, great lib!

I'm making an application that continually saves state-files to disk. I'd like to be able to use e.g. a DropBox folder as storage. If the files is modified from another computer and synched with dropbox i'd like to get a notification so I can reload my cached in app state. I would like to filter away my own local modifications and only get notified by other processes modifications. Is it possible to somehow get what process that modified the file? It would be nice to not have to constantly read the files after modifications and compare them to my local cache.

**Comment by daniel-pedersen** [comment]
It's not possible with kqueue to get the process that did a modification. You'd have to implement it yourself, but it sounds like you should be able to. You can filter out your own changes by either removing, writing changes, then re-adding the path every time you do a change, otherwise you have to implement some custom filtering in the change handler.
