### ISSUE TITLE
Get always "Write" notification!

### ISSUE THREAD

**Issue by schlemiel29** [daniel-pedersen/SKQueue#2]
Hi,
i tried this to get run. Every time I change a file in one of the folders tracked, I get a "Write" notification, even if I rename a file. You have a long list of different cases, but it seems 2 is the only number returned (= Write).
Is this a bug or a feature? ;-)
Dirk
P.S.: I'm using Xcode 7.3 and OSX 10.11.6

**Comment by daniel-pedersen** [comment]
Thank you for the question.

This is normal kqueue behavior. The "Write" occurs since the folder's modification date is updated when a file is renamed within it. More info on kqueue events can be found in the [man pages](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/kqueue.2.html) under the "EVFILT_VNODE" filter.
