### ISSUE TITLE
Moving folder containing watched files does not trigger notification

### ISSUE THREAD

**Issue by beeb** [daniel-pedersen/SKQueue#6]
Hey, first of all thanks for a great lib! I'm using it with success to watch files.

One thing I noticed is that, if I watch a folder and some files contained in it (I'm not even sure I can add folder paths but it doesn't throw an error and `isPathWatched` returns true for folders too), then moving the folder's location on disk will not post any notification, not on the folder path nor the files' paths.

Is there a way to make this work without too much hassle? It's weird that even the files inside the moved folder don't trigger a notif.

Thanks!

**Comment by daniel-pedersen** [comment]
Hello. So SKQueue is a very low-level library. It only exposes the functionality of kqueue, a kernel event notification library. I suggest you read up on the [man pages](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/kqueue.2.html) for kqueue to understand why SKQueue behaves like this. SKQueue uses the `EVFILT_VNODE` flag.

To explain your question, when you watch a directory, you basically get notifications on the corresponding [inode](https://en.wikipedia.org/wiki/Inode) of the path. That's why SKQueue works for any file-system object (even with weird stuff like /dev/null). Read up on that if you want to understand why SKQueue behaves the way it does. But what you're describing is not a bug.

I'm planning to work on implementing a complementary API that is a lot more user-friendly. Right now SKQueue only wraps the low level kqueue mechanism.

The advantage of this library is that it consumes insignificant resources, no CPU cycles until needed and each path to watch needs only a few bytes to watch.
