### ISSUE TITLE
it's show only first mod

### ISSUE THREAD

**Issue by lucabecchetti** [daniel-pedersen/SKQueue#7]
i see first mod, but then, I do not see nothing else if I continue modify!

**Comment by daniel-pedersen** [comment]
This is normal behaviour, more in depth explanations can be found in #6 and #2 

When a file is modified in the file system, the file descriptor has been closed, so it is invalid at that point. In other words, it behaves as the file is removed and a new file is created on each modification. This is the expected behaviour in kqueue, so this is not a bug.

The solution is to re-add the path at every modification. I've been planning to make an update to this library which will add common functionality like this.
