### ISSUE TITLE
Watch folder question

### ISSUE THREAD

**Issue by cheizer** [daniel-pedersen/SKQueue#8]
Hello,
I've been playing with SKQueue and noticed that the path is always the folder which is being watched. Not the file that was created or modified. Is this on purpose?

**Comment by daniel-pedersen** [comment]
Hey, thanks for your question!

SKQueue is a very simple wrapper around the kqueue kernel notification system. So the notifications are the same as those from kqueue ([read about it here](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/kqueue.2.html)). So this is on purpose, since that is the behavior of kqueue.

The solution is to watch for events on the folder and then add the files created for watching as well, it requires a bit of machinery. I'm considering developing a higher level Swift library that takes care of this.
